apiVersion: apps/v1
kind: Deployment
metadata:
  name: <app-name>-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <app-name>-db-container
  template:
    metadata:
      labels:
        app: <app-name>-db-container
        tier: backend
    spec:
      containers:
        - name: <app-name>-db-container
          image: postgres:alpine
          envFrom:
            - secretRef:
              name: <app-name>-credentials

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: <app-name>-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: <app-name>-volume-mount
          persistentVolumeClaim:
            claimName: <app-name>-pvc
