kind: PersistentVolume
apiVersion: v1
metadata:
  name: <app-name>-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: local
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/<app-name>-pv

