kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <app-name>-pvc
  labels:
    type: local
spec:
storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: <app-name>-pv