kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <app-name>-pvc
spec:
storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: <app-name>-pv